server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/springbootsecurity?serverTimezone=Asia/Seoul
    username: root
    password: toor
    
  security:
    user:
      name: test
      password: 1234   
    oauth2:      client:        registration:          google:
            client-id: 225357996300-fm2htbocp61t5hdgbekf6ntnh3f0i2nl.apps.googleusercontent.com
            client-secret: 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
            scope:            - email
            - profile
            
          facebook:
            client-id: 492499358554783
            client-secret: 4c0e6fb10fe0a18e8240a26cfaed36e9
            scope:            - email
            - profile
          naver:
            client-id: FoNL3qqixYlaIzeCDmp5
            client-secret: Na77PeguVl
            scope:            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json형태로 들고 올떄 response라는 key값으로 들고온다
      

mybatis:
  mapper-locations:
  - /mappers/*.xml












